### ISSUE TITLE
ApplicationNotResponding   sun.misc.Unsafe in park 

### ISSUE THREAD

**Issue by philos3** [getsentry/sentry-dart#1573]
### Platform

Dart

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4.1 22F82 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.10 on channel stable at /Users/XXX/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/linzechi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM F936U1 (mobile) • RFCTA0BR6DM • android-arm64 • Android 13 (API 33)
    • macOS (desktop)    • macos       • darwin-arm64  • macOS 13.4.1 22F82 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

### Version

7.8.0

### Steps to Reproduce

track by sentry， i dont know how to reproduce
https://sentry.deepcoin.ski/share/issue/c807d6131afe49a3badee5b2e5def0ee/

io.sentry.transport.AsyncHttpTransport.close

at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2109)
  at java.util.concurrent.ThreadPoolExecutor.awaitTermination (ThreadPoolExecutor.java:1486)
  at io.sentry.transport.AsyncHttpTransport.close (AsyncHttpTransport.java:143)
  at io.sentry.SentryClient.close (SentryClient.java:765)
  at io.sentry.Hub.close (Hub.java:351)
  at io.sentry.Sentry.init (Sentry.java:222)
  at io.sentry.Sentry.init (Sentry.java:147)
  at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:89)
  at io.sentry.android.core.SentryAndroid.init (SentryAndroid.java:70)
  at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk (SentryFlutterPlugin.kt:124)
  at io.sentry.flutter.SentryFlutterPlugin.onMethodCall (SentryFlutterPlugin.kt:55)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:262)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:295)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger (DartMessenger.java:319)
  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
 at android.app.ActivityThread.main (ActivityThread.java:8653)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

[stacktrace.log](https://github.com/getsentry/sentry-dart/files/12189963/stacktrace.log)

  

### Expected Result

no ApplicationNotResponding

### Actual Result

ApplicationNotResponding

### Are you willing to submit a PR?

None

**Comment by krystofwoldrich** [comment]
Hi, thank you for the message,
we will take a look at this. Note that due to schedules vacations the response time might be longer.

@markushi @romtsn From the stack trace it looks like `at io.sentry.transport.AsyncHttpTransport.close (AsyncHttpTransport.java:143)` executed during the Android SDK init caused the background ANR. Do you know when this could happen? 

Android SDK v6.23.0

**Comment by markushi** [comment]
@philos3 thanks for reaching out! 

I think this is a dup of https://github.com/getsentry/sentry-java/issues/2732, which has already been fixed and will be shipped with 7.0.0 (release date TBD).

But there might be other root causes for this, e.g.
- Are you using multiple crash reporting tools at the same time (e.g. Crashlytics and Sentry)?
- Do you initialize the SDK multiple times?

**Comment by romtsn** [comment]
This is the multi-init of the SDK case, should be addressed after resolving https://github.com/getsentry/sentry-java/issues/2864

**Comment by krystofwoldrich** [comment]
@philos3 Does any of these question applies to your setup?

> Are you using multiple crash reporting tools at the same time (e.g. Crashlytics and Sentry)?
> Do you initialize the SDK multiple times?

**Comment by philos3** [comment]
> getsentry/sentry-java#2864

I only initialize the SDK one time in flutter

**Comment by philos3** [comment]
I/Sentry  (25979): sentry-debug-meta.properties file was not found.
I/Sentry  (25979): java.io.FileNotFoundException: sentry-debug-meta.properties
I/Sentry  (25979): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
I/Sentry  (25979): 	at android.content.res.AssetManager.open(AssetManager.java:962)
I/Sentry  (25979): 	at android.content.res.AssetManager.open(AssetManager.java:939)
I/Sentry  (25979): 	at io.sentry.android.core.internal.debugmeta.AssetsDebugMetaLoader.loadDebugMeta(AssetsDebugMetaLoader.java:36)
I/Sentry  (25979): 	at io.sentry.Sentry.initConfigurations(Sentry.java:373)
I/Sentry  (25979): 	at io.sentry.Sentry.init(Sentry.java:210)
I/Sentry  (25979): 	at io.sentry.Sentry.init(Sentry.java:147)
I/Sentry  (25979): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
I/Sentry  (25979): 	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
I/Sentry  (25979): 	at io.sentry.flutter.SentryFlutterPlugin.initNativeSdk(SentryFlutterPlugin.kt:124)
I/Sentry  (25979): 	at io.sentry.flutter.SentryFlutterPlugin.onMethodCall(SentryFlutterPlugin.kt:55)
I/Sentry  (25979): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/Sentry  (25979): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/Sentry  (25979): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/Sentry  (25979): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/Sentry  (25979): 	at android.os.Handler.handleCallback(Handler.java:942)
I/Sentry  (25979): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/Sentry  (25979): 	at android.os.Looper.loopOnce(Looper.java:226)
I/Sentry  (25979): 	at android.os.Looper.loop(Looper.java:313)
I/Sentry  (25979): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
I/Sentry  (25979): 	at java.lang.reflect.Method.invoke(Native Method)
I/Sentry  (25979): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
I/Sentry  (25979): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Sentry  (25979): GlobalHubMode: 'true'
I/sentry-native(25979): using database path "/data/data/com.niocpeed.dna.test/cache/sentry/8dc659c789cfcbd9db4f69e045c60e1e62b15f0f/.sentry-native"
D/sentry-native(25979): starting backend
D/sentry-native(25979): processing and pruning old runs
W/Sentry  (25979): Current session is not ended, we'd need to end it.

**Comment by philos3** [comment]
<img width="756" alt="image" src="https://github.com/getsentry/sentry-dart/assets/8424317/9ed5a8ba-5417-4688-80d7-7c9737032a07">

**Comment by marandaneto** [comment]
@markushi @romtsn should I transfer this to the Java repo or close it? it's not related to the Flutter SDK and the ANR comes from the Android bits only.

**Comment by romtsn** [comment]
@marandaneto I'm not sure, I feel like this is something on the integration side of Flutter, because this looks like a strong case for multi-init of the SDK. We've fixed the underlying issue, but the root cause is probably this:

```
 io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage 
```
is this invoked only when app process/instance is created or also when going from background, for example (or any other case)?

**Comment by marandaneto** [comment]
@romtsn the fix is on Java v7 which is not released yet.

`IncomingMethodCallHandler` is just the bridge that allows calling native code, this is only called when the SDK is initialized or when a crumb/error or something is captured.

I agree that it looks like the SDK is being init multiple times, but the underlying problem is still on the Android SDK, specifically `AsyncHttpTransport.close`, so there's no actionable item on the Flutter side.

@philos3 your code snippet isn't complete, so we can't tell if you are calling `SentryFlutter.init` multiple times or not.
Maybe the method that calls `SentryFlutter.init` is being called multiple times, the SDK should be init. only once during the app's lifecycle, please double-check that (maybe a hot reload is causing this if you are testing on debug mode).

Once the Flutter SDK upgrades the Android SDK to v7, those ANRs will likely not be caused anymore/reduced, but its not published yet, so there's no actionable item on our side as of now.

**Comment by marandaneto** [comment]
@philos3 or @romtsn any follow up here?

**Comment by romtsn** [comment]
@marandaneto not from our side. You could move it to sentry-java, but we'd just close it, because we've fixed it in v7. We're hoping to ship it soon

**Comment by marandaneto** [comment]
Alright, once https://github.com/getsentry/sentry-java/releases v7 is released and the Flutter SDK is upgraded, we will close this issue, I will mark it as blocked for now.

**Comment by philos3** [comment]
maybe a hot reload is causing this，I just call SentryFlutter.init in the main.dart, which will only call once time 

![image](https://github.com/getsentry/sentry-dart/assets/8424317/415660b8-1814-4ebc-8f84-ccc3cd37d4dd)

![image](https://github.com/getsentry/sentry-dart/assets/8424317/113daecf-3df2-49dc-962f-50dc4831aee3)
